"""empty message

Revision ID: 708bfbfa3b30
Revises: 081bd7a2577b
Create Date: 2020-08-13 20:05:18.628927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708bfbfa3b30'
down_revision = '081bd7a2577b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
